sudo: required
services:
  - docker
  
before_install:
  # - docker build -t ray3110/docker-react -f Dockerfile.dev .  
  - docker build -t mytest -f Dockerfile.dev .

script:
  - docker run mytest npm run test -- --coverage