version: '3'
services:
  web:
    # build: .
    build:
      context: . 
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  # Specify custom test and Use 
  # docker-composer up --build to run the est
  test:
    build:
      context: . 
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

  